apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: t8
spec:
  entrypoint: workflow-dag
  volumes:
  - name: workflow-data
    emptyDir: {}
  templates:
    - name: workflow-dag
      dag:
        tasks:
        - name: start
          template: start-template
        - name: b
          dependencies: [start]
          template: b-template
        - name: c
          dependencies: [start]
          template: c-template
        - name: d
          dependencies: [b]
          template: d-template
        - name: e
          dependencies: [c]
          template: e-template
        - name: f
          dependencies: [d]
          template: f-template
        - name: g
          dependencies: [e]
          template: g-template
        - name: end
          dependencies: [f, g, b]
          template: end-template

    - name: start-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing Start task'; sleep 5.227"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: b-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing B task'; sleep 8.571"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: c-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing C task'; sleep 9.295"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: d-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing D task'; sleep 1.959"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: e-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing E task'; sleep 1.447"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: f-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing F task'; sleep 8.066"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: g-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing G task'; sleep 9.663"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: end-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing End task'; sleep 3.495"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data
