apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: t7
spec:
  entrypoint: workflow-dag
  volumes:
  - name: workflow-data
    emptyDir: {}
  templates:
    - name: workflow-dag
      dag:
        tasks:
        - name: start
          template: start-template
        - name: b
          dependencies: [start]
          template: b-template
        - name: c
          dependencies: [b]
          template: c-template
        - name: d
          dependencies: [b]
          template: d-template
        - name: e
          dependencies: [c]
          template: e-template
        - name: f
          dependencies: [d, g]
          template: f-template
        - name: g
          dependencies: [b]
          template: g-template
        - name: end
          dependencies: [e, f, d]
          template: end-template

    - name: start-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing Start task'; sleep 3.627"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: b-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing B task'; sleep 8.868"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: c-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing C task'; sleep 5.341"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: d-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing D task'; sleep 6.952"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: e-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing E task'; sleep 2.294"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: f-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing F task'; sleep 1.305"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: g-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing G task'; sleep 7.518"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: end-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing End task'; sleep 8.898"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data
