apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: t5
spec:
  entrypoint: workflow-dag
  volumes:
  - name: workflow-data
    emptyDir: {}
  templates:
    - name: workflow-dag
      dag:
        tasks:
        - name: start
          template: start-template
        - name: b
          dependencies: [start]
          template: b-template
        - name: c
          dependencies: [start]
          template: c-template
        - name: d
          dependencies: [b]
          template: d-template
        - name: e
          dependencies: [d]
          template: e-template
        - name: f
          dependencies: [e, i]
          template: f-template
        - name: g
          dependencies: [i, e]
          template: g-template
        - name: h
          dependencies: [f]
          template: h-template
        - name: i
          dependencies: [d]
          template: i-template
        - name: j
          dependencies: [e, i]
          template: j-template
        - name: k
          dependencies: [g]
          template: k-template
        - name: end
          dependencies: [h, k, f, c, j]
          template: end-template

    - name: start-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing Start task'; sleep 2.539"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: b-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing B task'; sleep 4.808"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: c-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing C task'; sleep 7.088"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: d-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing D task'; sleep 5.661"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: e-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing E task'; sleep 8.583"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: f-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing F task'; sleep 5.039"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: g-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing G task'; sleep 6.086"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: h-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing H task'; sleep 5.939"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: i-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing I task'; sleep 3.978"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: j-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing J task'; sleep 9.892"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: k-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing K task'; sleep 1.711"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: end-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing End task'; sleep 2.958"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data
