apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test2
spec:
  entrypoint: workflow-dag
  volumes:
  - name: workflow-data
    emptyDir: {}
  templates:
    - name: workflow-dag
      dag:
        tasks:
        - name: start
          template: start-template
        - name: b
          dependencies: [start]
          template: b-template
        - name: c
          dependencies: [b]
          template: c-template
        - name: d
          dependencies: [b]
          template: d-template
        - name: e
          dependencies: [c]
          template: e-template
        - name: f
          dependencies: [e, h]
          template: f-template
        - name: g
          dependencies: [f]
          template: g-template
        - name: h
          dependencies: [d, c]
          template: h-template
        - name: i
          dependencies: [h]
          template: i-template
        - name: j
          dependencies: [i]
          template: j-template
        - name: k
          dependencies: [b]
          template: k-template
        - name: end
          dependencies: [g, j, e, k]
          template: end-template

    - name: start-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing Start task'; sleep 9485"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: b-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing B task'; sleep 1807"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: c-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing C task'; sleep 2914"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: d-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing D task'; sleep 1908"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: e-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing E task'; sleep 4723"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: f-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing F task'; sleep 2716"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: g-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing G task'; sleep 3721"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: h-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing H task'; sleep 5997"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: i-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing I task'; sleep 3461"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: j-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing J task'; sleep 7288"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: k-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing K task'; sleep 8731"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: end-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing End task'; sleep 8690"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data
