apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
spec:
  entrypoint: workflow-dag
  # Limit total workflow parallelism
  parallelism: 4
  volumes:
  - name: workflow-data
    emptyDir: {}
  templates:
    - name: workflow-dag
      dag:
        tasks:
        - name: start
          template: start-template
        - name: b
          dependencies: [start]
          template: b-template
        - name: c
          dependencies: [b, k]
          template: c-template
        - name: d
          dependencies: [k]
          template: d-template
        - name: e
          dependencies: [c]
          template: e-template
        - name: f
          dependencies: [d]
          template: f-template
        - name: g
          dependencies: [e]
          template: g-template
        - name: h
          dependencies: [j]
          template: h-template
        - name: i
          dependencies: [f, e]
          template: i-template
        - name: j
          dependencies: [b]
          template: j-template
        - name: k
          dependencies: [start, j]
          template: k-template
        - name: end
          dependencies: [g, i, d, h]
          template: end-template

    - name: start-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing Start task'; sleep 0.068"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: b-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing B task'; sleep 0.016"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: c-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing C task'; sleep 0.021"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: d-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing D task'; sleep 0.047"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: e-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing E task'; sleep 0.075"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: f-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing F task'; sleep 0.091"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: g-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing G task'; sleep 0.058"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: h-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing H task'; sleep 0.027"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: i-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing I task'; sleep 0.034"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: j-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing J task'; sleep 0.027"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: k-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing K task'; sleep 0.044"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: end-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing End task'; sleep 0.098"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data
