apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test1
spec:
  entrypoint: workflow-dag
  # Limit total workflow parallelism
  parallelism: 2
  volumes:
  - name: workflow-data
    emptyDir: {}
  templates:
    - name: workflow-dag
      dag:
        tasks:
        - name: start
          template: start-template
        - name: b
          dependencies: [start]
          template: b-template
        - name: c
          dependencies: [start]
          template: c-template
        - name: d
          dependencies: [b]
          template: d-template
        - name: e
          dependencies: [c, b]
          template: e-template
        - name: end
          dependencies: [d, e, b]
          template: end-template

    - name: start-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing Start task'; sleep 0.6219"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: b-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing B task'; sleep 0.1716"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: c-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing C task'; sleep 0.6091"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: d-template
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing D task'; sleep 0.3697"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: e-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing E task'; sleep 0.6264"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data

    - name: end-template
      nodeSelector:
        kubernetes.io/hostname: wf-scheduling  # Critical path node
      container:
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["echo 'Executing End task'; sleep 0.2121"]
        volumeMounts:
        - name: workflow-data
          mountPath: /data
